
import { EMAIL_TEMPLATE } from './emailTemplate';
import { EMAIL_TEMPLATE_VISIONARY } from './emailTemplateVisionary';
import { EMAIL_TEMPLATE_PRODUCT_FOCUS } from './emailTemplateProductFocus';
import { EMAIL_TEMPLATE_SOCIAL_PROOF } from './emailTemplateSocialProof';
import { EMAIL_TEMPLATE_INVITATION } from './emailTemplateInvitation';

// This is the rich promotional template provided by the user.
const EMAIL_TEMPLATE_PROMOTIONAL = `
<!DOCTYPE html><html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" lang="fr"><head><title></title><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><!--[if mso]>
<xml><w:WordDocument xmlns:w="urn:schemas-microsoft-com:office:word"><w:DontUseAdvancedTypographyReadingMail/></w:WordDocument>
<o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch><o:AllowPNG/></o:OfficeDocumentSettings></xml>
<![endif]--><!--[if !mso]><!--><link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&amp;display=swap" rel="stylesheet" type="text/css"><!--<![endif]--><style>
*{box-sizing:border-box}body{margin:0;padding:0}a[x-apple-data-detectors]{color:inherit!important;text-decoration:inherit!important}#MessageViewBody a{color:inherit;text-decoration:none}p{line-height:inherit}.desktop_hide,.desktop_hide table{mso-hide:all;display:none;max-height:0;overflow:hidden}.image_block img+div{display:none}sub,sup{font-size:75%;line-height:0} @media (max-width:620px){.mobile_hide{display:none}.row-content{width:100%!important}.stack .column{width:100%;display:block}.mobile_hide{min-height:0;max-height:0;max-width:0;overflow:hidden;font-size:0}.desktop_hide,.desktop_hide table{display:table!important;max-height:none!important}.reverse{display:table;width:100%}.reverse .column.first{display:table-footer-group!important}.reverse .column.last{display:table-header-group!important}.row-15 td.column.first .border{padding:20px 0 0}.row-15 td.column.last .border{padding:10px 20px}.row-2 .column-1 .block-1.image_block td.pad{padding:0 0 30px!important}.row-2 .column-1 .block-3.text_block td.pad{padding:5px 10px 10px 0!important}.row-2 .column-2 .block-1.image_block .alignment div{margin:0 auto!important}.row-2 .column-1 .block-2.heading_block h1{font-size:32px!important}.row-21 .column-1 .block-2.button_block span,.row-6 .column-1 .block-2.button_block span{font-size:15px!important;line-height:30px!important}.row-12 .column-1 .block-1.text_block td.pad,.row-18 .column-1 .block-1.text_block td.pad{padding:10px 0 0!important}.row-15 .column-2 .block-1.text_block td.pad{padding:0 0 10px!important}.row-21 .column-1 .block-1.text_block td.pad{padding:15px 0 10px!important}.row-21 .column-1 .block-3.text_block td.pad{padding:25px 0!important}.row-2 .column-1{padding:40px 20px 0!important}.row-2 .column-2{padding:0!important}.row-8 .column-1{padding:30px 20px 20px!important}.row-10 .column-1{padding:15px 15px 0!important}.row-12 .column-1{padding:20px!important}.row-12 .column-2{padding:0 20px 10px!important}.row-15 .column-1 .border,.row-18 .column-2,.row-21 .column-1{padding:0 20px!important}.row-18 .column-1{padding:5px 20px 20px!important}}
</style><!--[if mso ]><style>sup, sub { font-size: 100% !important; } sup { mso-text-raise:10% } sub { mso-text-raise:-10% }</style> <![endif]--><meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1" /><title>Découvrez en avant-première Virtual Training Place</title><link rel="stylesheet" href="/css/htmlemail.css"></head><body class="body" style="margin:0;background-color:#f7f7f9;padding:0;-webkit-text-size-adjust:none;text-size-adjust:none"><table class="nl-container" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#f7f7f9"><tbody><tr><td><table 
class="row row-1 mobile_hide" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#f7f7f9;border-radius:0;color:#000;width:600px;margin:0 auto" width="600"><tbody><tr><td class="column column-1" width="58.333333333333336%" 
style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-left:20px;padding-top:60px;vertical-align:top"><table class="image_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="padding-bottom:25px;width:100%;padding-right:0;padding-left:0"><div class="alignment" align="left"><div style="max-width:148.5px"><img src="{{logoUrl}}" alt="" width="148.5" /></div></div></td></tr></table><table class="heading_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="padding-bottom:5px;text-align:center;width:100%"><h1 
style="margin:0;color:#555;direction:ltr;font-family:'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif;font-size:34px;font-weight:700;letter-spacing:normal;line-height:1;text-align:left;margin-top:0;margin-bottom:0;mso-line-height-alt:34px"><span class="tinyMce-placeholder" style="word-break: break-word;">{{main_title}}</span></h1></td></tr>
</table><table class="text_block block-3" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad" style="padding-bottom:10px;padding-right:10px;padding-top:10px"><div style="font-family:Arial,sans-serif"><div class style="font-size:14px;font-family:'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif;mso-line-height-alt:16.8px;color:#555;line-height:1.2"><p 
style="margin:0;font-size:14px;mso-line-height-alt:16.8px"><span style="word-break: break-word; font-size: 20px;">{{intro_paragraph}}</span></p></div></div></td></tr></table></td><td class="column column-2" width="41.666666666666664%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-right:10px;vertical-align:bottom"><table class="image_block block-1" width="100%" border="0" cellpadding="0" 
cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="width:100%;padding-right:0;padding-left:0"><div class="alignment" align="left"><div style="max-width:240px"><img src="https://1x2t1.mjt.lu/img2/1x2t1/668f7425-5544-4f28-9eea-44e925b69b82/content" alt="" width="240" /></div></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><!--[if !mso]><!--><table
 class="row row-2 desktop_hide" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;mso-hide:all;display:none;max-height:0;overflow:hidden"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;mso-hide:all;display:none;max-height:0;overflow:hidden;background-color:#f7f7f9;border-radius:0;color:#000;width:600px;margin:0 auto" width="600"><tbody><tr><td class="column column-1" width="58.333333333333336%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-left:20px;padding-top:60px;vertical-align:top"><table class="image_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" 
role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;mso-hide:all;display:none;max-height:0;overflow:hidden"><tr><td class="pad" style="padding-bottom:25px;width:100%;padding-right:0;padding-left:0"><div class="alignment" align="left"><div style="max-width:165px"><img src="{{logoUrl}}" alt="" width="165" /></div></div></td></tr></table><table 
class="heading_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;mso-hide:all;display:none;max-height:0;overflow:hidden"><tr><td class="pad" style="padding-bottom:5px;text-align:center;width:100%"><h1 
style="margin:0;color:#555;direction:ltr;font-family:'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif;font-size:34px;font-weight:700;letter-spacing:normal;line-height:1;text-align:left;margin-top:0;margin-bottom:0;mso-line-height-alt:34px"><span class="tinyMce-placeholder" style="word-break: break-word;">{{main_title}}</span></h1></td></tr>
</table><table class="text_block block-3" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word;mso-hide:all;display:none;max-height:0;overflow:hidden"><tr><td class="pad" style="padding-bottom:10px;padding-right:10px;padding-top:10px"><div style="font-family:Arial,sans-serif"><div class 
style="font-size:14px;font-family:'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif;mso-line-height-alt:16.8px;color:#555;line-height:1.2"><p style="margin:0;font-size:14px;mso-line-height-alt:16.8px"><span style="word-break: break-word; font-size: 20px;">{{intro_paragraph}}</span></p></div></div></td></tr></table></td><td class="column column-2" width="41.666666666666664%" 
style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-right:10px;vertical-align:bottom"><table class="image_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;mso-hide:all;display:none;max-height:0;overflow:hidden"><tr><td class="pad" style="width:100%;padding-right:0;padding-left:0"><div class="alignment" align="left"><div style="max-width:204px"><img src="https://1x2t1.mjt.lu/img2/1x2t1/678a4277-ac0a-4e7a-8d2c-d16b7d2820d8/content" alt="" width="204" /></div></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><!--<![endif]--><table class="row row-3 mobile_hide" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" align="center" 
border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#8950c3;border-radius:13px;color:#000;width:600px;margin:0 auto" width="600"><tbody><tr><td class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-left:25px;padding-right:25px;vertical-align:top"><table class="text_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad" style="padding-bottom:10px;padding-top:10px"><div style="font-family:Arial,sans-serif"><div class style="font-size:14px;font-family:'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif;mso-line-height-alt:16.8px;color:#fff;line-height:1.2"><p style="margin:0;font-size:14px;text-align:center;mso-line-height-alt:16.8px">La formation évolue. Vos collaborateurs veulent apprendre autrement.</p></div></div></td>
</tr></table></td></tr></tbody></table></td></tr></tbody></table><!--[if !mso]><!--><table class="row row-4 desktop_hide" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;mso-hide:all;display:none;max-height:0;overflow:hidden"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;mso-hide:all;display:none;max-height:0;overflow:hidden;background-color:#8950c3;border-radius:0;color:#000;width:600px;margin:0 auto" width="600"><tbody><tr><td class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-left:25px;padding-right:25px;vertical-align:top"><table class="text_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word;mso-hide:all;display:none;max-height:0;overflow:hidden"><tr><td class="pad" style="padding-bottom:10px;padding-top:10px"><div style="font-family:Arial,sans-serif"><div class style="font-size:14px;font-family:'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif;mso-line-height-alt:21px;color:#fff;line-height:1.5"><p style="margin:0;font-size:14px;text-align:center;mso-line-height-alt:21px">
La formation évolue. Vos collaborateurs veulent apprendre autrement.</p></div></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><!--<![endif]--><table class="row row-5 mobile_hide" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;background-color:#f7f7f9;border-radius:0;color:#000;width:600px;margin:0 auto" width="600"><tbody><tr><td class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-bottom:25px;padding-left:20px;padding-right:20px;vertical-align:top"><table class="text_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad" style="padding-bottom:20px;padding-top:30px"><div style="font-family:Arial,sans-serif"><div class style="font-size:14px;font-family:'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif;mso-line-height-alt:21px;color:#555;line-height:1.5"><p style="margin:0;font-size:14px;mso-line-height-alt:24px"><span style="word-break: break-word; font-size: 16px;">Bonjour {{first_name}},</span><br><br>
<span style="word-break: break-word; font-size: 16px;">{{body_paragraph}}</span></p></div></div></td></tr></table><table class="button_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" 
style="padding-bottom:10px;padding-top:10px;text-align:left"><div class="alignment" align="left"><a href="{{cta_link}}" target="_blank" style="color:#ffffff;text-decoration:none;"><!--[if mso]>
<v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word"  href="{{cta_link}}"  style="height:45px;width:283px;v-text-anchor:middle;" arcsize="69%" fillcolor="{{primaryColor}}">
<v:stroke dashstyle="Solid" weight="0px" color="{{primaryColor}}"/>
<w:anchorlock/>
<v:textbox inset="0px,0px,0px,1px">
<center dir="false" style="color:#ffffff;font-family:Arial, sans-serif;font-size:16px">
<![endif]-->
<span class="button" style="background-color: {{primaryColor}}; mso-shading: transparent; border-bottom: 0px solid transparent; border-left: 0px solid transparent; border-radius: 31px; border-right: 0px solid transparent; border-top: 0px solid transparent; color: #ffffff; display: inline-block; font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; mso-border-alt: none; padding-bottom: 7px; padding-top: 6px; padding-left: 25px; padding-right: 25px; text-align: center; width: auto; word-break: keep-all; letter-spacing: normal;"><span style="word-break: break-word; line-height: 32px;">{{cta_text}}</span></span>
<!--[if mso]></center></v:textbox></v:roundrect><![endif]--></a></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><!--[if !mso]><!--><table class="row row-6 desktop_hide" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;mso-hide:all;display:none;max-height:0;overflow:hidden"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" 
role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;mso-hide:all;display:none;max-height:0;overflow:hidden;background-color:#f7f7f9;border-radius:0;color:#000;width:600px;margin:0 auto" width="600"><tbody><tr><td class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-bottom:45px;padding-left:20px;padding-right:20px;padding-top:10px;vertical-align:top"><table class="text_block block-1" width="100%" border="0" 
cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word;mso-hide:all;display:none;max-height:0;overflow:hidden"><tr><td class="pad" style="padding-bottom:20px;padding-top:30px"><div style="font-family:Arial,sans-serif"><div class style="font-size:14px;font-family:'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif;mso-line-height-alt:21px;color:#555;line-height:1.5"><p style="margin:0;font-size:14px;mso-line-height-alt:24px">
<span style="word-break: break-word; font-size: 16px;">Bonjour {{first_name}},</span><br><br><span style="word-break: break-word; font-size: 16px;">{{body_paragraph}}</span></p></div></div></td></tr></table><table class="button_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;mso-hide:all;display:none;max-height:0;overflow:hidden"><tr><td 
class="pad" style="padding-bottom:10px;padding-top:10px;text-align:left"><div class="alignment" align="left"><a href="{{cta_link}}" target="_blank" style="color:#ffffff;text-decoration:none;"><!--[if mso]>
<v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word"  href="{{cta_link}}"  style="height:45px;width:283px;v-text-anchor:middle;" arcsize="69%" fillcolor="{{primaryColor}}">
<v:stroke dashstyle="Solid" weight="0px" color="{{primaryColor}}"/>
<w:anchorlock/>
<v:textbox inset="0px,0px,0px,1px">
<center dir="false" style="color:#ffffff;font-family:Arial, sans-serif;font-size:16px">
<![endif]-->
<span class="button" style="background-color: {{primaryColor}}; mso-shading: transparent; border-bottom: 0px solid transparent; border-left: 0px solid transparent; border-radius: 31px; border-right: 0px solid transparent; border-top: 0px solid transparent; color: #ffffff; display: inline-block; font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; mso-border-alt: none; padding-bottom: 7px; padding-top: 6px; padding-left: 25px; padding-right: 25px; text-align: center; width: auto; word-break: keep-all; letter-spacing: normal;"><span style="word-break: break-word; line-height: 32px;">{{cta_text}}</span></span>
<!--[if mso]></center></v:textbox></v:roundrect><![endif]--></a></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><!--<![endif]--><table class="row row-7 mobile_hide" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;background-color:#f7f7f9;border-radius:0;color:#000;width:600px;margin:0 auto" width="600"><tbody><tr><td class="column column-1" width="50%" 
style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;background-color:#8950c3;border-bottom:5px solid #f7f7f9;border-left:5px solid #f7f7f9;border-right:5px solid #f7f7f9;border-top:5px solid #f7f7f9;padding-bottom:20px;padding-left:20px;padding-right:20px;padding-top:30px;vertical-align:top"><table class="text_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr>
<td class="pad" style="padding-bottom:10px"><div style="font-family:Arial,sans-serif"><div class style="font-size:14px;font-family:'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif;mso-line-height-alt:19.599999999999998px;color:#555;line-height:1.4"><p style="margin:0;font-size:17px;mso-line-height-alt:28px"><span style="word-break: break-word; font-size: 20px;"><strong><span style="word-break: break-word; color: #ffffff;">Vous le savez :</span></strong></span></p></div></div></td></tr>
</table><table class="text_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad"><div style="font-family:Arial,sans-serif"><div class style="font-size:14px;font-family:'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif;mso-line-height-alt:19.599999999999998px;color:#555;line-height:1.4"><p style="margin:0;font-size:17px;mso-line-height-alt:23.799999999999997px">
<span style="word-break: break-word; color: #ffffff;"><span style="word-break: break-word; font-size: 15px;"><em>L</em></span><span style="word-break: break-word; font-size: 17px;"><span style="word-break: break-word; font-size: 15px;"><em><span style="word-break: break-word;">es modules e-learning traditionnels peinent à susciter l’engagement.</span></em></span><br></span></span></p></div></div></td></tr></table><table class="divider_block block-3" width="100%" border="0" cellpadding="0" 
cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="padding-top:55px"><div class="alignment" align="center"><table border="0" cellpadding="0" cellspacing="0" role="presentation" width="100%" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="divider_inner" style="font-size:1px;line-height:1px;border-top:1px dashed #f8e5e5"><span style="word-break: break-word;">&#8202;</span></td></tr></table></div></td></tr></table></td><td 
class="column column-2" width="50%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;background-color:#00c9b5;border-bottom:5px solid #f7f7f9;border-left:5px solid #f7f7f9;border-right:5px solid #f7f7f9;border-top:5px solid #f7f7f9;padding-bottom:20px;padding-left:20px;padding-right:20px;padding-top:30px;vertical-align:top"><table class="text_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad" style="padding-bottom:10px"><div style="font-family:Arial,sans-serif"><div class style="font-size:14px;font-family:'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif;mso-line-height-alt:19.599999999999998px;color:#555;line-height:1.4"><p style="margin:0;font-size:17px;mso-line-height-alt:28px">
<span style="word-break: break-word; color: #ffffff; font-size: 20px;"><span style="word-break: break-word;"><strong>Résultat :</strong></span></span></p></div></div></td></tr></table><table class="text_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad"><div style="font-family:Arial,sans-serif"><div class 
style="font-size:14px;font-family:'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif;mso-line-height-alt:19.599999999999998px;color:#555;line-height:1.4"><p style="margin:0;font-size:17px;mso-line-height-alt:21px">
<span style="word-break: break-word; font-size: 15px;"><em><span style="word-break: break-word; color: #ffffff;"><span style="word-break: break-word;">M</span><span style="word-break: break-word;">oins de 15 % de taux de participation, des apprenants passifs et un impact limité sur le terrain.</span></span></em></span></p></div></div></td></tr></table><table class="divider_block block-3" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="padding-top:30px"><div class="alignment" align="center"><table border="0" cellpadding="0" cellspacing="0" role="presentation" width="100%" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="divider_inner" style="font-size:1px;line-height:1px;border-top:1px dashed #f8e5e5"><span style="word-break: break-word;">&#8202;</span></td></tr></table></div></td></tr></table></td></tr></tbody></table></td></tr></tbody>
</table><!--[if !mso]><!--><table class="row row-8 desktop_hide" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;mso-hide:all;display:none;max-height:0;overflow:hidden"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;mso-hide:all;display:none;max-height:0;overflow:hidden;background-color:#f7f7f9;border-radius:0;color:#000;width:600px;margin:0 auto" width="600"><tbody><tr><td class="column column-1" width="50%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;background-color:#8950c3;border-bottom:6px solid #f7f7f9;padding-bottom:20px;padding-left:20px;padding-right:20px;padding-top:30px;vertical-align:top"><table 
class="text_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word;mso-hide:all;display:none;max-height:0;overflow:hidden"><tr><td class="pad" style="padding-bottom:10px"><div style="font-family:Arial,sans-serif"><div class style="font-size:14px;font-family:'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif;mso-line-height-alt:19.599999999999998px;color:#555;line-height:1.4"><p 
style="margin:0;font-size:17px;text-align:center;mso-line-height-alt:28px"><span style="word-break: break-word; font-size: 20px;"><strong><span style="word-break: break-word; color: #ffffff;">Vous le savez :</span></strong></span></p></div></div></td></tr></table><table class="text_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word;mso-hide:all;display:none;max-height:0;overflow:hidden">
<tr><td class="pad"><div style="font-family:Arial,sans-serif"><div class style="font-size:14px;font-family:'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif;mso-line-height-alt:19.599999999999998px;color:#555;line-height:1.4"><p style="margin:0;font-size:17px;text-align:center;mso-line-height-alt:23.799999999999997px">
<span style="word-break: break-word; color: #ffffff;"><span style="word-break: break-word; font-size: 15px;"><em>L</em></span><span style="word-break: break-word; font-size: 17px;"><span style="word-break: break-word; font-size: 15px;"><em><span style="word-break: break-word;">es modules e-learning traditionnels peinent à susciter l’engagement.</span></em></span><br></span></span></p></div></div></td></tr></table><table class="divider_block block-3" width="100%" border="0" cellpadding="0" 
cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;mso-hide:all;display:none;max-height:0;overflow:hidden"><tr><td class="pad" style="padding-top:55px"><div class="alignment" align="center"><table border="0" cellpadding="0" cellspacing="0" role="presentation" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;mso-hide:all;display:none;max-height:0;overflow:hidden"><tr><td class="divider_inner" 
style="font-size:1px;line-height:1px;border-top:1px dashed #f8e5e5"><span style="word-break: break-word;">&#8202;</span></td></tr></table></div></td></tr></table></td><td class="column column-2" width="50%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;background-color:#00c9b5;padding-bottom:20px;padding-left:20px;padding-right:20px;padding-top:30px;vertical-align:top"><table class="text_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" 
role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word;mso-hide:all;display:none;max-height:0;overflow:hidden"><tr><td class="pad" style="padding-bottom:10px"><div style="font-family:Arial,sans-serif"><div class style="font-size:14px;font-family:'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif;mso-line-height-alt:19.599999999999998px;color:#555;line-height:1.4"><p style="margin:0;font-size:17px;text-align:center;mso-line-height-alt:28px">
<span style="word-break: break-word; color: #ffffff; font-size: 20px;"><span style="word-break: break-word;"><strong>Résultat :</strong></span></span></p></div></div></td></tr></table><table class="text_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word;mso-hide:all;display:none;max-height:0;overflow:hidden"><tr><td class="pad"><div style="font-family:Arial,sans-serif"><div class 
style="font-size:14px;font-family:'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif;mso-line-height-alt:19.599999999999998px;color:#555;line-height:1.4"><p style="margin:0;font-size:17px;text-align:center;mso-line-height-alt:21px">
<span style="word-break: break-word; font-size: 15px;"><em><span style="word-break: break-word; color: #ffffff;"><span style="word-break: break-word;">M</span><span style="word-break: break-word;">oins de 15 % de taux de participation, des apprenants passifs et un impact limité sur le terrain.</span></span></em></span></p></div></div></td></tr></table><table class="divider_block block-3" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;mso-hide:all;display:none;max-height:0;overflow:hidden"><tr><td class="pad" style="padding-top:30px"><div class="alignment" align="center"><table border="0" cellpadding="0" cellspacing="0" role="presentation" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;mso-hide:all;display:none;max-height:0;overflow:hidden"><tr><td class="divider_inner" style="font-size:1px;line-height:1px;border-top:1px dashed #f8e5e5">
<span style="word-break: break-word;">&#8202;</span></td></tr></table></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><!--<![endif]--><table class="row row-9 mobile_hide" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;background-color:#f7f7f9;border-radius:0;color:#000;width:600px;margin:0 auto" width="600"><tbody><tr><td class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-bottom:10px;padding-top:10px;vertical-align:top"><table class="image_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" 
style="width:100%;padding-right:0;padding-left:0"><div class="alignment" align="center"><div style="max-width:60px"><img src="https://1x2t1.mjt.lu/img2/1x2t1/81b3a901-4157-4de0-9e23-0c5bf344d3e2/content" alt="" width="60" /></div></div></td></tr></table><table class="heading_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" 
style="text-align:center;width:100%"><h1 style="margin:0;color:#555;direction:ltr;font-family:'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif;font-size:30px;font-weight:400;letter-spacing:normal;line-height:1.1;text-align:center;margin-top:0;margin-bottom:0;mso-line-height-alt:33px"><span class="tinyMce-placeholder" style="word-break: break-word;">Virtual Training Place<br>va changer la donne</span></h1></td></tr></table></td></tr></tbody></table></td></tr></tbody></table>
<!--[if !mso]><!--><table class="row row-10 desktop_hide" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;mso-hide:all;display:none;max-height:0;overflow:hidden"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;mso-hide:all;display:none;max-height:0;overflow:hidden;background-color:#f7f7f9;border-radius:0;color:#000;width:600px;margin:0 auto" width="600"><tbody><tr><td class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-bottom:30px;padding-top:30px;vertical-align:top"><table class="image_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;mso-hide:all;display:none;max-height:0;overflow:hidden"><tr><td class="pad" style="width:100%;padding-right:0;padding-left:0"><div class="alignment" align="center"><div style="max-width:50px"><img src="https://1x2t1.mjt.lu/img2/1x2t1/81b3a901-4157-4de0-9e23-0c5bf344d3e2/content" style="display:block;height:auto;border:0;width:100%" width="50" alt title height="auto"></div></div></td></tr></table><table class="heading_block block-2" width="100%" 
border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;mso-hide:all;display:none;max-height:0;overflow:hidden"><tr><td class="pad" style="text-align:center;width:100%"><h1 style="margin:0;color:#555;direction:ltr;font-family:'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif;font-size:30px;font-weight:400;letter-spacing:normal;line-height:1.1;text-align:center;margin-top:0;margin-bottom:0;mso-line-height-alt:33px">
<span class="tinyMce-placeholder" style="word-break: break-word;">Virtual Training Place va changer la donne</span></h1></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><!--<![endif]--><table class="row row-11 mobile_hide" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" 
role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#f7f7f9;border-radius:0;color:#000;width:600px;margin:0 auto" width="600"><tbody><tr><td class="column column-1" width="50%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-bottom:20px;padding-left:20px;padding-right:20px;padding-top:25px;vertical-align:middle"><table class="text_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad"><div style="font-family:Arial,sans-serif"><div class style="font-size:14px;font-family:'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif;mso-line-height-alt:21px;color:#555;line-height:1.5"><p style="margin:0;font-size:14px;mso-line-height-alt:22.5px">
<span style="word-break: break-word; font-size: 15px;">Déjà plus de <span style="word-break: break-word; color: #8950c3;"><strong>250 parcours métiers</strong></span>, autour du management, des soft skills, des RH, du bien-être au travail et bien plus encore.</span></p></div></div></td></tr></table></td><td class="column column-2" width="50%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:middle"><table class="image_block block-1" width="100%" 
border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="width:100%;padding-right:0;padding-left:0"><div class="alignment" align="center"><div style="max-width:300px"><img src="https://1x2t1.mjt.lu/img2/1x2t1/d84febe5-4d7d-4681-8e47-a2d3c58f805c/content" style="display:block;height:auto;border:0;width:100%" width="300" alt title height="auto"></div></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table>
<!--[if !mso]><!--><table class="row row-12 desktop_hide" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;mso-hide:all;display:none;max-height:0;overflow:hidden"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;mso-hide:all;display:none;max-height:0;overflow:hidden;background-color:#f7f7f9;border-radius:0;color:#000;width:600px;margin:0 auto" width="600"><tbody><tr><td class="column column-1" width="50%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-bottom:20px;padding-left:20px;padding-right:20px;padding-top:35px;vertical-align:middle"><table class="text_block block-1" width="100%" border="0" cellpadding="0" 
cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word;mso-hide:all;display:none;max-height:0;overflow:hidden"><tr><td class="pad" style="padding-bottom:10px;padding-top:10px"><div style="font-family:Arial,sans-serif"><div class style="font-size:14px;font-family:'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif;mso-line-height-alt:21px;color:#555;line-height:1.5"><p style="margin:0;font-size:14px;text-align:left;mso-line-height-alt:22.5px">
<span style="word-break: break-word; font-size: 15px;">Déjà plus de <span style="word-break: break-word; color: #8950c3;"><strong>250 parcours métiers</strong></span>, autour du management, des soft skills, des RH, du bien-être au travail et bien plus encore.</span></p></div></div></td></tr></table></td><td class="column column-2" width="50%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:middle"><table class="image_block block-1" width="100%" 
border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;mso-hide:all;display:none;max-height:0;overflow:hidden"><tr><td class="pad" style="width:100%;padding-right:0;padding-left:0"><div class="alignment" align="center"><div style="max-width:300px"><img src="https://1x2t1.mjt.lu/img2/1x2t1/d84febe5-4d7d-4681-8e47-a2d3c58f805c/content" style="display:block;height:auto;border:0;width:100%" width="300" alt title height="auto"></div></div></td></tr>
</table></td></tr></tbody></table></td></tr></tbody></table><!--<![endif]--><table class="row row-13" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#f7f7f9;border-radius:0;color:#000;width:600px;margin:0 auto" 
width="600"><tbody><tr><td class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top"><table class="divider_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="padding-bottom:10px;padding-left:5px;padding-right:5px;padding-top:5px"><div class="alignment" align="center"><table border="0" cellpadding="0" 
cellspacing="0" role="presentation" width="100%" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="divider_inner" style="font-size:1px;line-height:1px;border-top:1px dashed #bbb"><span style="word-break: break-word;">&#8202;</span></td></tr></table></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-14 mobile_hide" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#f7f7f9;border-radius:0;color:#000;width:600px;margin:0 auto" width="600"><tbody><tr><td class="column column-1" width="50%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-top:10px;vertical-align:middle"><table 
class="image_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="width:100%;padding-right:0;padding-left:0"><div class="alignment" align="center"><div style="max-width:285px"><img src="https://1x2t1.mjt.lu/img2/1x2t1/eab8e312-6de6-44e4-be26-3402296e3eec/content" style="display:block;height:auto;border:0;width:100%" width="285" alt title height="auto"></div></div>
</td></tr></table></td><td class="column column-2" width="50%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-bottom:10px;padding-left:20px;padding-right:20px;vertical-align:middle"><table class="text_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad"><div style="font-family:Arial,sans-serif"><div class 
style="font-size:14px;font-family:'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif;mso-line-height-alt:21px;color:#555;line-height:1.5"><p style="margin:0;font-size:14px;mso-line-height-alt:22.5px"><span style="word-break: break-word; font-size: 15px;">Des contenus gamifiés générant <span style="word-break: break-word; color: #8950c3;"><strong>jusqu’à 3x plus d’engagement</strong></span>.</span></p></div></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table>
<!--[if !mso]><!--><table class="row row-15 desktop_hide" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;mso-hide:all;display:none;max-height:0;overflow:hidden"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;mso-hide:all;display:none;max-height:0;overflow:hidden;background-color:#f7f7f9;border-radius:0;color:#000;width:600px;margin:0 auto" width="600"><tbody><tr class="reverse"><td class="column column-1 first" width="50%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-top:20px;vertical-align:middle"><div class="border"><table class="image_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" 
role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;mso-hide:all;display:none;max-height:0;overflow:hidden"><tr><td class="pad" style="width:100%;padding-right:0;padding-left:0"><div class="alignment" align="center"><div style="max-width:285px"><img src="https://1x2t1.mjt.lu/img2/1x2t1/eab8e312-6de6-44e4-be26-3402296e3eec/content" style="display:block;height:auto;border:0;width:100%" width="285" alt title height="auto"></div></div></td></tr></table></div></td>
<td class="column column-2 last" width="50%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-bottom:10px;padding-left:20px;padding-right:20px;padding-top:10px;vertical-align:middle"><div class="border"><table class="text_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word;mso-hide:all;display:none;max-height:0;overflow:hidden"><tr><td class="pad" 
style="padding-bottom:10px;padding-top:10px"><div style="font-family:Arial,sans-serif"><div class style="font-size:14px;font-family:'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif;mso-line-height-alt:21px;color:#555;line-height:1.5"><p style="margin:0;font-size:14px;mso-line-height-alt:22.5px">
<span style="word-break: break-word; font-size: 15px;">Des contenus gamifiés générant <span style="word-break: break-word; color: #8950c3;"><strong>jusqu’à 3x plus d’engagement</strong></span>.</span></p></div></div></td></tr></table></div></td></tr></tbody></table></td></tr></tbody></table><!--<![endif]--><table class="row row-16" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table 
class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#f7f7f9;border-radius:0;color:#000;width:600px;margin:0 auto" width="600"><tbody><tr><td class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top"><table class="divider_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" 
role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="padding-bottom:10px;padding-left:10px;padding-right:10px;padding-top:15px"><div class="alignment" align="center"><table border="0" cellpadding="0" cellspacing="0" role="presentation" width="100%" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="divider_inner" style="font-size:1px;line-height:1px;border-top:1px dashed #bbb"><span style="word-break: break-word;">&#8202;</span></td></tr></table>
</div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-17 mobile_hide" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;background-color:#f7f7f9;border-radius:0;color:#000;width:600px;margin:0 auto" width="600"><tbody><tr><td class="column column-1" width="50%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-bottom:20px;padding-left:20px;padding-right:20px;padding-top:20px;vertical-align:middle"><table class="text_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad"><div style="font-family:Arial,sans-serif"><div class style="font-size:14px;font-family:'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif;mso-line-height-alt:21px;color:#555;line-height:1.5"><p style="margin:0;font-size:14px;mso-line-height-alt:22.5px">
<span style="word-break: break-word; font-size: 15px;">La possibilité de <strong><span style="word-break: break-word; color: #8950c3;">personnaliser</span> </strong>un parcours existant, <span style="word-break: break-word; color: #8950c3;"><strong>2x moins cher</strong></span> et <span style="word-break: break-word; color: #8950c3;"><strong>3x plus rapide</strong></span> que du sur-mesure classique.</span></p></div></div></td></tr></table></td><td class="column column-2" width="50%" 
style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:middle"><table class="image_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="padding-left:10px;width:100%;padding-right:0"><div class="alignment" align="left"><div style="max-width:255px"><img src="https://1x2t1.mjt.lu/img2/1x2t1/6656be7e-4441-4fa5-865f-47cbf587b1b5/content" 
style="display:block;height:auto;border:0;width:100%" width="255" alt title height="auto"></div></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><!--[if !mso]><!--><table class="row row-18 desktop_hide" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;mso-hide:all;display:none;max-height:0;overflow:hidden"><tbody><tr><td><table class="row-content stack" align="center" border="0" 
cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;mso-hide:all;display:none;max-height:0;overflow:hidden;background-color:#f7f7f9;border-radius:0;color:#000;width:600px;margin:0 auto" width="600"><tbody><tr><td class="column column-1" width="50%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-bottom:20px;padding-left:20px;padding-right:20px;padding-top:35px;vertical-align:middle"><table 
class="text_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word;mso-hide:all;display:none;max-height:0;overflow:hidden"><tr><td class="pad" style="padding-bottom:10px;padding-top:10px"><div style="font-family:Arial,sans-serif"><div class style="font-size:14px;font-family:'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif;mso-line-height-alt:21px;color:#555;line-height:1.5"><p 
style="margin:0;font-size:14px;mso-line-height-alt:22.5px"><span style="word-break: break-word; font-size: 15px;">La possibilité de <strong><span style="word-break: break-word; color: #8950c3;">personnaliser</span> </strong>un parcours existant, <span style="word-break: break-word; color: #8950c3;"><strong>2x moins cher</strong></span> et <span style="word-break: break-word; color: #8950c3;"><strong>3x plus rapide</strong></span> que du sur-mesure classique.</span></p></div></div></td></tr>
</table></td><td class="column column-2" width="50%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:middle"><table class="image_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;mso-hide:all;display:none;max-height:0;overflow:hidden"><tr><td class="pad" style="padding-left:10px;width:100%;padding-right:0"><div class="alignment" align="left"><div 
style="max-width:255px"><img src="https://1x2t1.mjt.lu/img2/1x2t1/6656be7e-4441-4fa5-865f-47cbf587b1b5/content" style="display:block;height:auto;border:0;width:100%" width="255" alt title height="auto"></div></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><!--<![endif]--><table class="row row-19" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table 
class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#f7f7f9;border-radius:0;color:#000;width:600px;margin:0 auto" width="600"><tbody><tr><td class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top"><table class="divider_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" 
role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="padding-bottom:10px;padding-left:10px;padding-right:10px;padding-top:15px"><div class="alignment" align="center"><table border="0" cellpadding="0" cellspacing="0" role="presentation" width="100%" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="divider_inner" style="font-size:1px;line-height:1px;border-top:1px dashed #bbb"><span style="word-break: break-word;">&#8202;</span></td></tr></table>
</div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-20 mobile_hide" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;background-color:#f7f7f9;border-radius:0;color:#000;width:600px;margin:0 auto" width="600"><tbody><tr><td class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-left:20px;padding-right:20px;vertical-align:top"><table class="text_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word">
<tr><td class="pad" style="padding-bottom:10px;padding-top:25px"><div style="font-family:Arial,sans-serif"><div class style="font-size:14px;font-family:'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif;mso-line-height-alt:21px;color:#555;line-height:1.5"><p style="margin:0;font-size:14px;mso-line-height-alt:24px">
<span style="word-break: break-word; font-size: 16px;">👇Cliquez ici pour découvrir <span style="word-break: break-word; color: #8950c3;"><strong>Virtual Training Place</strong></span> en avant-première !</span></p></div></div></td></tr></table><table class="button_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="padding-bottom:10px;padding-top:10px;text-align:left"><div 
class="alignment" align="left"><a href="https://vts.seriousfactory.com/virtual-training-place" target="_blank" style="color:#ffffff;text-decoration:none;"><!--[if mso]>
<v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word"  href="https://vts.seriousfactory.com/virtual-training-place"  style="height:45px;width:283px;v-text-anchor:middle;" arcsize="63%" fillcolor="#3AAEE0">
<v:stroke dashstyle="Solid" weight="0px" color="#3AAEE0"/>
<w:anchorlock/>
<v:textbox inset="0px,0px,0px,1px">
<center dir="false" style="color:#ffffff;font-family:Arial, sans-serif;font-size:16px">
<![endif]-->
<span class="button" style="background-color: #3AAEE0; mso-shading: transparent; border-bottom: 0px solid transparent; border-left: 0px solid transparent; border-radius: 28px; border-right: 0px solid transparent; border-top: 0px solid transparent; color: #ffffff; display: inline-block; font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; mso-border-alt: none; padding-bottom: 7px; padding-top: 6px; padding-left: 25px; padding-right: 25px; text-align: center; width: auto; word-break: keep-all; letter-spacing: normal;"><span style="word-break: break-word; line-height: 32px;">Découvrir Virtual Training Place</span></span>
<!--[if mso]></center></v:textbox></v:roundrect><![endif]--></a></div></td></tr></table><table class="text_block block-3" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad" style="padding-bottom:10px;padding-top:30px"><div style="font-family:Arial,sans-serif"><div class 
style="font-size:14px;font-family:'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif;mso-line-height-alt:21px;color:#555;line-height:1.5"><p style="margin:0;font-size:16px;mso-line-height-alt:24px"><span style="word-break: break-word; font-size: 16px;">À très bientôt,<br></span><span style="word-break: break-word; font-size: 16px;"><strong><span style="word-break: break-word;">L’équipe Serious Factory</span></strong></span></p></div></div></td></tr></table><table 
class="image_block block-4" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="padding-bottom:40px;padding-top:20px;width:100%;padding-right:0;padding-left:0"><div class="alignment" align="center"><div style="max-width:112px"><img src="https://1x2t1.mjt.lu/img2/1x2t1/84af04f9-bff6-4f05-a8eb-8576dd1570e3/content" style="display:block;height:auto;border:0;width:100%" width="112" alt title height="auto">
</div></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class="text_block mobile_hide" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word;">
  <tr>
    <td class="pad" style="padding:10px 20px 20px;">
      <div style="font-family:'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif; font-size:10px; color:#999; text-align:center; line-height:1.4;">
        Cet email a été envoyé à {{email}}, 
        <a href="[[UNSUB_LINK_FR]]" target="_blank" style="color:#999; text-decoration:underline;">
          cliquez ici pour vous désabonner
        </a>.
      </div>
    </td>
  </tr>
</table>
<!--[if !mso]><!--><table class="row row-21 desktop_hide" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;mso-hide:all;display:none;max-height:0;overflow:hidden"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;mso-hide:all;display:none;max-height:0;overflow:hidden;background-color:#f7f7f9;border-radius:0;color:#000;width:600px;margin:0 auto" width="600"><tbody><tr><td class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-left:20px;padding-right:20px;padding-top:5px;vertical-align:top"><table class="text_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" 
role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word;mso-hide:all;display:none;max-height:0;overflow:hidden"><tr><td class="pad" style="padding-bottom:10px;padding-top:30px"><div style="font-family:Arial,sans-serif"><div class style="font-size:14px;font-family:'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif;mso-line-height-alt:21px;color:#555;line-height:1.5"><p style="margin:0;font-size:14px;mso-line-height-alt:24px">
<span style="word-break: break-word; font-size: 16px;">👇Cliquez ici pour découvrir <span style="word-break: break-word; color: #8950c3;"><strong>Virtual Training Place</strong></span> en avant-première !</span></p></div></div></td></tr></table><table class="button_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;mso-hide:all;display:none;max-height:0;overflow:hidden"><tr><td class="pad" 
style="padding-bottom:10px;padding-top:10px;text-align:left"><div class="alignment" align="left"><a href="https://vts.seriousfactory.com/virtual-training-place" target="_blank" style="color:#ffffff;text-decoration:none;"><!--[if mso]>
<v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word"  href="https://vts.seriousfactory.com/virtual-training-place"  style="height:45px;width:283px;v-text-anchor:middle;" arcsize="63%" fillcolor="#3AAEE0">
<v:stroke dashstyle="Solid" weight="0px" color="#3AAEE0"/>
<w:anchorlock/>
<v:textbox inset="0px,0px,0px,1px">
<center dir="false" style="color:#ffffff;font-family:Arial, sans-serif;font-size:16px">
<![endif]-->
<span class="button" style="background-color: #3AAEE0; mso-shading: transparent; border-bottom: 0px solid transparent; border-left: 0px solid transparent; border-radius: 28px; border-right: 0px solid transparent; border-top: 0px solid transparent; color: #ffffff; display: inline-block; font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; mso-border-alt: none; padding-bottom: 7px; padding-top: 6px; padding-left: 25px; padding-right: 25px; text-align: center; width: auto; word-break: keep-all; letter-spacing: normal;"><span style="word-break: break-word; line-height: 32px;">Découvrir Virtual Training Place</span></span>
<!--[if mso]></center></v:textbox></v:roundrect><![endif]--></a></div></td></tr></table><table class="text_block block-3" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word;mso-hide:all;display:none;max-height:0;overflow:hidden"><tr><td class="pad" style="padding-bottom:25px;padding-top:45px"><div style="font-family:Arial,sans-serif"><div class 
style="font-size:14px;font-family:'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif;mso-line-height-alt:21px;color:#555;line-height:1.5"><p style="margin:0;font-size:16px;mso-line-height-alt:24px"><span style="word-break: break-word; font-size: 16px;">À très bientôt,<br></span><span style="word-break: break-word; font-size: 16px;"><strong><span style="word-break: break-word;">L’équipe Serious Factory</span></strong></span></p></div></div></td></tr></table><table 
class="image_block block-4" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;mso-hide:all;display:none;max-height:0;overflow:hidden"><tr><td class="pad" style="padding-bottom:40px;padding-top:20px;width:100%;padding-right:0;padding-left:0"><div class="alignment" align="center"><div style="max-width:99px"><img src="https://1x2t1.mjt.lu/img2/1x2t1/84af04f9-bff6-4f05-a8eb-8576dd1570e3/content" 
style="display:block;height:auto;border:0;width:100%" width="99" alt title height="auto"></div></div></td></tr></table><table class="text_block" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation"
style="mso-table-lspace:0;mso-table-rspace:0; word-break:break-word; mso-hide:all; display:none; max-height:none; overflow:hidden;">
  <tr>
    <td class="pad" style="padding:10px 20px 30px;">
      <div style="font-family:'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif; font-size:10px; color:#999; text-align:center; line-height:1.4;">
        Cet email a été envoyé à {{email}}, 
        <a href="[[UNSUB_LINK_FR]]" target="_blank" style="color:#999; text-decoration:underline;">
          cliquez ici pour vous désabonner
        </a>.
      </div>
    </td>
  </tr>
</table>
</td></tr></tbody></table></td></tr></tbody></table><!-- End --></body></html>
`;


export const ALL_EMAIL_TEMPLATES = {
  STANDARD: {
    name: "LE STANDARD",
    description: "Template simple et efficace, mono-colonne. Idéal pour des communications directes, du suivi, ou quand le message est plus important que le design complexe.",
    template: EMAIL_TEMPLATE
  },
  PROMOTIONAL: {
    name: "LE PROMOTIONNEL / LANCEMENT",
    description: "Template riche et visuel, multi-colonnes. Parfait pour une annonce majeure, un lancement de produit ou une campagne marketing d'envergure nécessitant de présenter de multiples facettes d'une offre.",
    template: EMAIL_TEMPLATE_PROMOTIONAL
  },
  VISIONARY: {
    name: "LE VISIONNAIRE",
    description: "Idéal pour le thought leadership et les articles de fond. Met l'accent sur la typographie, la lisibilité et la crédibilité du contenu. Design minimaliste.",
    template: EMAIL_TEMPLATE_VISIONARY
  },
  PRODUCT_FOCUS: {
    name: "LE FOCUS PRODUIT",
    description: "Conçu pour présenter un produit ou une fonctionnalité. Structure claire avec un visuel 'héros', une liste de bénéfices et un appel à l'action direct.",
    template: EMAIL_TEMPLATE_PRODUCT_FOCUS
  },
  SOCIAL_PROOF: {
    name: "LA PREUVE SOCIALE",
    description: "Utilisé pour renforcer la crédibilité via des études de cas ou des témoignages. Met en avant une citation client forte et des résultats chiffrés (KPIs).",
    template: EMAIL_TEMPLATE_SOCIAL_PROOF
  },
  INVITATION: {
    name: "L'INVITATION",
    description: "Template optimisé pour maximiser les inscriptions à un événement (webinaire, conférence). Structure très directe, centrée sur les informations logistiques et les bénéfices pour les participants.",
    template: EMAIL_TEMPLATE_INVITATION
  }
};
